"""add unique constraint for channel

Revision ID: 5d6794e48454
Revises: 1fe825412c46
Create Date: 2024-02-18 16:12:08.225580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6794e48454'
down_revision: Union[str, None] = '1fe825412c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channels', ['name'])
    op.add_column('contact_channels', sa.Column('value', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_channels', 'value')
    op.drop_constraint(None, 'channels', type_='unique')
    # ### end Alembic commands ###
