"""make contact channel as unique

Revision ID: 9396c600d926
Revises: 5e3c08af009b
Create Date: 2024-02-18 22:26:31.445738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9396c600d926'
down_revision: Union[str, None] = '5e3c08af009b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contacts_channels', ['channel_value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts_channels', type_='unique')
    # ### end Alembic commands ###
